services:
  backend:
    build: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
  nginx:
    build: nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
