version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_USER=$PG_USER
      - POSTGRES_DATABASE=$PG_DATABASE
    volumes:
      - $PG_DATA_DIR:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    restart: always
    ports:
      - "3000:5000"

