version: "3.8"
services:
  back:
    build: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
  front:
    build: frontend
    restart: unless-stopped
    ports:
      - "3000:5000"

